#!/usr/bin/env python3

import pygame
from pygame.locals import *
from burnlib.scriptlib import KeyParser
import sys
import os.path

CONFDIR = "conf"
THEMEDIR = "themes"

# The default size of the board (give a number as the first argument to change)
BOARDSIZE = 9

# This looks good
RESOLUTION = (512, 512)

# This looks okay, but the cursor is a few pixels off
# RESOLUTION = (640, 480)

# This looks bad ATM, since the lines on the board are misaligned
# RESOLUTION = (1024, 768)

# If you run it in a window, you have room for the GnuGo GTP-text as well :-)
FULLSCREEN = False

def main():
    global CONFDIR
    global THEMEDIR
    global BOARDSIZE

    # is the argument the boardsize or a filename?
    arg = " ".join(sys.argv[1:])
    filename = ""
    try:
        BOARDSIZE = int(arg)
    except ValueError:
        filename = arg

    if filename:
        # finding size based on the filename
        # (could include other sizes in the future)
        with open(filename) as file:
            data = file.read()
            if "SZ[9]" in data:
                BOARDSIZE = 9
            elif "SZ[13]" in data:
                BOARDSIZE = 13
            elif "SZ[19]" in data:
                BOARDSIZE = 19

    kp = KeyParser(os.path.join(CONFDIR, "keybindings.conf"), RESOLUTION, FULLSCREEN, BOARDSIZE, THEMEDIR, CONFDIR)

    windowtitle = 'Monkeyjump'

    # is the argument a filename?
    if filename:
        print(f"Loading {filename}...")
        # load the sgf
        kp.parser.fc("loadsgf", filename)
        print("ok")
        # change the window title
        windowtitle += f' - {filename}'

    # set the window title
    pygame.display.set_caption(windowtitle)

    # limit the type of events allowed
    pygame.event.set_allowed(KEYUP)

    while True:
        pygame.event.pump()
        event = pygame.event.wait()
        if event.type == QUIT:
            break
        elif event.type == KEYUP:
            kp(event.key)
        elif event.type == MOUSEMOTION:
            kp.parser.fc("mousepos", *pygame.mouse.get_pos())
        mousepressed = pygame.mouse.get_pressed()
        # Update the mouse-position if a button is pressed
        if 1 in mousepressed:
            kp.parser.fc("mousepos", *pygame.mouse.get_pos())
        kp(mousepressed)
        kp.refresh()

    pygame.quit()

if __name__ == "__main__":
    main()
